"""
Expanded Stimulus Set for Statistical Power

100 sentence triplets (exact repeat, no repeat, semantic near-miss)
designed to cover diverse:
- Token types (nouns, verbs, adjectives, proper nouns)
- Sentence structures (SVO, complex, embedded clauses)
- Semantic domains (nature, science, urban, domestic, abstract)
- Token frequencies (common + rare words)
"""

# Category 1: EXACT REPEATS — a key content word appears twice
EXACT_REPEAT = [
    # Original 15
    "The cat sat on the rug and the cat slept peacefully",
    "A bright star appeared above the mountain and the star shone all night",
    "The doctor examined the patient carefully and the doctor prescribed medicine",
    "My old friend called yesterday and my old friend invited me to dinner",
    "The river flows through the valley and the river feeds the lake below",
    "A tall tree stands in the garden and the tree provides shade",
    "The musician played the piano beautifully and the musician took a bow",
    "Heavy rain fell on the city and the rain caused flooding everywhere",
    "The student read the book quickly and the student wrote a summary",
    "A large ship sailed across the ocean and the ship reached port safely",
    "The painter mixed the colors carefully and the painter created a masterpiece",
    "An old clock hung on the wall and the clock chimed every hour",
    "The scientist conducted the experiment twice and the scientist published results",
    "A small bird landed on the fence and the bird sang a melody",
    "The chef prepared the meal slowly and the chef served it hot",
    # Additional 85
    "The professor lectured for two hours and the professor answered every question",
    "A golden retriever bounded through the park and the retriever fetched the ball",
    "The pilot checked the instruments carefully and the pilot began the descent",
    "An ancient temple stood at the summit and the temple attracted many visitors",
    "The detective reviewed the evidence thoroughly and the detective identified the suspect",
    "A young dancer performed on stage and the dancer received a standing ovation",
    "The engineer designed a new bridge and the engineer supervised its construction",
    "Heavy snow covered the entire village and the snow lasted through March",
    "The author wrote the novel over three years and the author dedicated it to family",
    "A curious fox appeared near the cabin and the fox watched us silently",
    "The mayor announced a new policy today and the mayor faced tough questions",
    "An elegant chandelier hung from the ceiling and the chandelier illuminated the ballroom",
    "The goalkeeper blocked the penalty kick and the goalkeeper celebrated with teammates",
    "A powerful earthquake struck the coast and the earthquake damaged hundreds of buildings",
    "The librarian organized the collection meticulously and the librarian helped every patron",
    "A magnificent whale surfaced near the boat and the whale sprayed water skyward",
    "The mechanic inspected the engine thoroughly and the mechanic replaced the worn parts",
    "An unexpected letter arrived this morning and the letter contained surprising news",
    "The farmer harvested the wheat in August and the farmer stored it in barns",
    "A bright comet appeared in the evening sky and the comet was visible for weeks",
    "The journalist investigated the corruption scandal and the journalist published a detailed expose",
    "A stray kitten wandered into the garage and the kitten found shelter from the storm",
    "The surgeon performed the operation successfully and the surgeon spoke with the family afterward",
    "An old photograph fell from the album and the photograph showed a forgotten relative",
    "The violinist tuned her instrument backstage and the violinist played flawlessly during the concert",
    "A dense fog rolled in from the harbor and the fog obscured the entire coastline",
    "The archaeologist uncovered ancient pottery fragments and the archaeologist documented every finding",
    "A young eagle soared above the canyon and the eagle spotted prey far below",
    "The carpenter built a beautiful bookshelf and the carpenter finished it with dark walnut stain",
    "An important meeting was scheduled for noon and the meeting lasted well into the evening",
    "The volcano erupted without any warning and the volcano sent ash clouds miles high",
    "A talented sculptor shaped the marble block and the sculptor revealed an astonishing figure",
    "The astronomer observed a distant galaxy cluster and the astronomer recorded the spectral data",
    "An enormous bear emerged from the forest and the bear ambled toward the river",
    "The conductor raised the baton slowly and the conductor began the symphony with a whisper",
    "A mysterious stranger appeared at the door and the stranger asked for directions to town",
    "The gardener planted roses along the path and the gardener watered them every morning",
    "An abandoned factory stood at the edge of town and the factory was scheduled for demolition",
    "The ambassador delivered a speech at the summit and the ambassador proposed a new alliance",
    "A playful dolphin leaped beside the kayak and the dolphin followed us for a mile",
    "The electrician rewired the entire basement and the electrician installed new circuit breakers",
    "An unusual butterfly landed on my hand and the butterfly stayed for several minutes",
    "The philosopher debated the nature of consciousness and the philosopher wrote extensively about free will",
    "A severe drought affected the entire region and the drought destroyed most of the crops",
    "The pianist practiced the sonata for months and the pianist performed it at Carnegie Hall",
    "An intricate mosaic decorated the entrance hall and the mosaic depicted scenes from ancient mythology",
    "The firefighter rushed into the burning building and the firefighter rescued three trapped residents",
    "A gentle breeze rustled through the wheat field and the breeze carried the scent of lavender",
    "The mathematician proved the conjecture after decades and the mathematician received international recognition",
    "An ornate mirror hung above the fireplace and the mirror reflected the entire drawing room",
    "The translator worked on the manuscript for a year and the translator preserved every subtle nuance",
    "A massive glacier carved through the mountain range and the glacier left deep valleys behind",
    "The biologist discovered a new species of moth and the biologist named it after her mentor",
    "An express train departed from the central station and the train arrived exactly on schedule",
    "The photographer captured the sunset over the desert and the photographer sold the image to a magazine",
    "A sudden thunderstorm interrupted the outdoor wedding and the thunderstorm passed within twenty minutes",
    "The blacksmith forged a sword from raw iron and the blacksmith tempered it in cold water",
    "An exotic orchid bloomed in the greenhouse and the orchid attracted dozens of admiring visitors",
    "The senator introduced a controversial bill and the senator defended it during heated debate",
    "A coral reef stretched for miles along the coast and the reef supported thousands of marine species",
    "The poet composed verses by candlelight and the poet published them in a slim volume",
    "An enormous wave crashed against the seawall and the wave flooded the promenade completely",
    "The locksmith opened the antique safe carefully and the locksmith found old documents inside",
    "A brilliant rainbow arched across the valley and the rainbow faded slowly as the sun set",
    "The geologist examined the rock formation closely and the geologist estimated it was millions of years old",
    "An elegant heron stood motionless in the shallows and the heron struck at a fish suddenly",
    "The plumber fixed the leaking pipe overnight and the plumber charged a reasonable price",
    "A rare eclipse darkened the afternoon sky and the eclipse lasted for nearly four minutes",
    "The weaver created tapestries of extraordinary detail and the weaver sold them at the local market",
    "An icy wind swept down from the mountains and the wind brought the first snow of winter",
    "The curator arranged the exhibition thoughtfully and the curator wrote descriptions for every piece",
    "A towering redwood dominated the forest clearing and the redwood was estimated to be two thousand years old",
    "The chemist analyzed the unknown compound and the chemist determined its molecular structure",
    "An old bridge spanned the wide river and the bridge had been standing for three centuries",
    "The beekeeper tended the hives each morning and the beekeeper harvested golden honey in autumn",
    "A sleek submarine descended into the abyss and the submarine mapped the ocean floor below",
    "The jeweler examined the diamond under bright light and the jeweler declared it virtually flawless",
    "An ancient manuscript was found in the monastery and the manuscript contained previously unknown texts",
    "The quarterback threw a perfect spiral downfield and the quarterback led the team to victory",
    "A dense jungle surrounded the hidden temple and the jungle had reclaimed most of the ruins",
    "The optician fitted the new lenses precisely and the optician adjusted the frame for comfort",
    "An ivory tower rose above the medieval castle and the tower offered views of three counties",
    "The florist arranged the bouquet with great care and the florist delivered it before noon",
    "A huge iceberg drifted south through the strait and the iceberg calved several smaller pieces",
    "The cartographer mapped the uncharted territory and the cartographer noted every river and ridge",
    "An agile monkey swung through the canopy overhead and the monkey chattered at us from above",
    "The sommelier recommended a vintage burgundy and the sommelier decanted it at the table",
    "A fierce blizzard trapped the climbers on the ridge and the blizzard lasted through the night",
    "The midwife delivered the baby safely at home and the midwife stayed until morning",
    "An ornamental fountain splashed in the courtyard and the fountain was carved from white marble",
]

# Category 2: NO REPEATS — all content words unique
NO_REPEAT = [
    # Original 15
    "The cat sat on the rug while a dog slept peacefully nearby",
    "A bright star appeared above the mountain as clouds drifted slowly past",
    "The doctor examined the patient carefully before writing a new prescription",
    "My old friend called yesterday with exciting news about a promotion",
    "The river flows through the valley carrying leaves and small branches downstream",
    "A tall tree stands in the garden providing shelter for nesting birds",
    "The musician played the piano beautifully receiving applause from every listener",
    "Heavy rain fell on the city flooding several streets and parking lots",
    "The student read the book quickly finishing before anyone else had started",
    "A large ship sailed across the ocean encountering dolphins along its path",
    "The painter mixed the colors carefully producing shades nobody had seen before",
    "An old clock hung on the wall ticking steadily through quiet afternoons",
    "The scientist conducted the experiment twice achieving consistent and reliable measurements",
    "A small bird landed on the fence chirping loudly at passing strangers",
    "The chef prepared the meal slowly adding herbs and spices with care",
    # Additional 85
    "The professor lectured for two hours while graduate students took careful notes",
    "A golden retriever bounded through the park chasing leaves blown by autumn winds",
    "The pilot checked every instrument before beginning a smooth descent toward home",
    "An ancient temple stood proudly at the summit attracting pilgrims from distant lands",
    "The detective reviewed each piece of evidence before questioning several key witnesses",
    "A young dancer performed brilliantly on stage earning praise from seasoned critics",
    "The engineer designed an innovative bridge that withstood extreme environmental conditions",
    "Heavy snow covered every rooftop in the village creating a pristine white landscape",
    "The author labored over each chapter for months before submitting to eager publishers",
    "A curious fox appeared beside our cabin watching silently from behind tall grass",
    "The mayor held a press conference announcing significant budget changes for next quarter",
    "An elegant chandelier dominated the ceiling casting warm light across polished marble floors",
    "The goalkeeper anticipated every shot blocking three penalties in spectacular fashion",
    "A powerful earthquake rattled the coastal region toppling bridges and cracking foundations",
    "The librarian curated an impressive collection helping visitors discover rare literary treasures",
    "A magnificent whale surfaced gracefully near our vessel exhaling a towering column of mist",
    "The mechanic diagnosed every issue quickly replacing worn components with factory parts",
    "An unexpected package arrived early this morning containing a handwritten note from abroad",
    "The farmer planted wheat across fifty acres expecting a bountiful harvest by autumn",
    "A bright comet streaked through the evening sky visible to observers across three continents",
    "The journalist pursued every lead relentlessly uncovering corruption at the highest levels",
    "A stray kitten wandered through our garage seeking warmth during a terrible rainstorm",
    "The surgeon completed a delicate procedure lasting seven hours before briefing anxious relatives",
    "An old photograph slipped from behind a dusty frame revealing faces long forgotten",
    "The violinist performed each passage flawlessly earning a prolonged standing ovation from critics",
    "A dense fog rolled across the harbor obscuring every vessel anchored along the waterfront",
    "The archaeologist brushed away centuries of sediment revealing pottery fragments of remarkable beauty",
    "A young eagle circled high above the canyon scanning rocky ledges for potential prey",
    "The carpenter assembled a sturdy bookshelf finishing every surface with rich walnut varnish",
    "An important summit convened at noon drawing diplomats from more than forty nations",
    "The volcano erupted spectacularly without warning launching massive ash plumes into clear skies",
    "A talented sculptor transformed raw marble into a breathtaking figure of extraordinary grace",
    "The astronomer pointed a powerful telescope skyward capturing faint light from billions of miles away",
    "An enormous bear lumbered out of dense woodland heading directly toward a shallow creek",
    "The conductor raised a silver baton signaling violins to begin with a hushed tremolo",
    "A mysterious visitor appeared at our front porch asking politely about rooms for rent",
    "The gardener cultivated roses along every walkway irrigating them faithfully each summer morning",
    "An abandoned warehouse loomed at the edge of town awaiting scheduled demolition next spring",
    "The ambassador addressed dozens of world leaders proposing ambitious reforms to existing treaties",
    "A playful dolphin leaped repeatedly beside our kayak following closely for nearly a mile",
    "The electrician replaced old wiring throughout the basement installing modern safety breakers everywhere",
    "An unusual moth landed gently on my palm remaining completely still for several minutes",
    "The philosopher examined consciousness from multiple angles writing prolifically about autonomy and choice",
    "A prolonged drought devastated croplands across every county leaving farmers desperate for relief",
    "The pianist rehearsed a demanding sonata daily preparing for a prestigious international competition",
    "An intricate mosaic adorned the vestibule walls depicting legendary heroes from classical antiquity",
    "The firefighter charged into a blazing structure pulling three residents from collapsing upper floors",
    "A gentle breeze swept across golden wheat fields carrying fragrant hints of distant lavender",
    "The mathematician solved a famously intractable conjecture receiving acclaim from colleagues worldwide",
    "An ornate gilded mirror dominated the space above a carved stone hearth in the parlor",
    "The translator labored meticulously over each paragraph preserving subtle literary qualities throughout",
    "A colossal glacier slowly advanced through mountain passes carving deep channels in granite bedrock",
    "The biologist identified a previously unknown insect naming it after a beloved college mentor",
    "An express locomotive departed from the central hub arriving punctually at every scheduled stop",
    "The photographer framed a stunning desert landscape selling prints to several prominent galleries",
    "A sudden downpour interrupted outdoor festivities scattering guests beneath nearby awnings and porches",
    "The blacksmith heated raw iron in a roaring forge shaping it into a fine blade",
    "An exotic bloom opened inside a humid greenhouse drawing enthusiastic crowds of botanical admirers",
    "The senator stood before packed chambers defending a polarizing proposal amid fierce opposition",
    "A vast coral formation extended for miles beneath turquoise waters sheltering countless marine organisms",
    "The poet scribbled verses beneath a flickering candle collecting them later in a slim anthology",
    "An enormous swell crashed violently against a concrete barrier sending spray high over pedestrians",
    "The locksmith carefully manipulated an antique mechanism discovering yellowed papers hidden within a vault",
    "A vivid rainbow stretched from horizon to horizon fading gradually as late afternoon sunlight dimmed",
    "The geologist surveyed exposed strata along a steep cliff estimating their age at several million years",
    "An elegant wading bird stood frozen in shallow water striking at unsuspecting fish below",
    "The plumber repaired a burst pipe overnight presenting a fair invoice the following morning",
    "A rare celestial alignment darkened midday skies captivating observers who gathered in open fields",
    "The weaver produced richly patterned textiles offering them for sale at a bustling weekend bazaar",
    "An arctic gust descended from high peaks bringing flurries that signaled the approach of winter",
    "The curator designed an engaging exhibition writing detailed commentary for every displayed artifact",
    "A towering conifer dominated a sunlit forest clearing estimated by experts to exceed two millennia",
    "The chemist isolated an unfamiliar molecule elucidating its complex three dimensional atomic arrangement",
    "An old stone viaduct spanned the broad waterway having served travelers for over three hundred years",
    "The apiarist inspected buzzing colonies at dawn collecting surplus golden nectar by early autumn",
    "A sleek underwater vessel plunged into abyssal depths charting previously unmapped regions of the seabed",
    "The gemologist scrutinized a polished stone beneath intense illumination certifying its exceptional clarity and cut",
    "An ancient scroll surfaced inside a remote monastery revealing passages that scholars had never encountered",
    "The quarterback launched a spiraling throw connecting with a streaking receiver for the winning score",
    "A verdant wilderness encircled crumbling ruins where tropical vegetation had gradually reclaimed every surface",
    "The optometrist calibrated precision lenses adjusting lightweight titanium frames for maximum patient comfort",
    "An ivory spire jutted above medieval fortifications affording panoramic vistas across three neighboring counties",
    "The florist assembled an exquisite arrangement dispatching it by courier well before the noon deadline",
    "A colossal ice mass drifted southward through the narrow strait fracturing into numerous smaller segments",
    "The mapmaker charted unexplored terrain meticulously recording every creek and ridgeline with painstaking accuracy",
]

# Category 3: SEMANTIC NEAR-MISSES — synonym/related word replaces the repeated token
SEMANTIC_NEAR = [
    # Original 15
    "The cat sat on the rug and the kitten slept peacefully nearby",
    "A bright star appeared above the mountain and the sun shone all day",
    "The doctor examined the patient carefully and the physician prescribed medicine",
    "My old friend called yesterday and my close companion invited me over",
    "The river flows through the valley and the stream feeds the lake",
    "A tall tree stands in the garden and the bush provides shade",
    "The musician played the piano beautifully and the pianist took a bow",
    "Heavy rain fell on the city and the downpour caused flooding everywhere",
    "The student read the book quickly and the pupil wrote a summary",
    "A large ship sailed across the ocean and the vessel reached port",
    "The painter mixed the colors carefully and the artist created a masterpiece",
    "An old clock hung on the wall and the watch chimed every hour",
    "The scientist conducted the experiment twice and the researcher published results",
    "A small bird landed on the fence and the sparrow sang a melody",
    "The chef prepared the meal slowly and the cook served it hot",
    # Additional 85
    "The professor lectured for two hours and the instructor answered every question",
    "A golden retriever bounded through the park and the dog fetched the ball",
    "The pilot checked the instruments carefully and the aviator began the descent",
    "An ancient temple stood at the summit and the shrine attracted many visitors",
    "The detective reviewed the evidence thoroughly and the investigator identified the suspect",
    "A young dancer performed on stage and the ballerina received a standing ovation",
    "The engineer designed a new bridge and the architect supervised its construction",
    "Heavy snow covered the entire village and the blizzard lasted through March",
    "The author wrote the novel over three years and the writer dedicated it to family",
    "A curious fox appeared near the cabin and the vixen watched us silently",
    "The mayor announced a new policy today and the governor faced tough questions",
    "An elegant chandelier hung from the ceiling and the fixture illuminated the ballroom",
    "The goalkeeper blocked the penalty kick and the keeper celebrated with teammates",
    "A powerful earthquake struck the coast and the tremor damaged hundreds of buildings",
    "The librarian organized the collection meticulously and the archivist helped every patron",
    "A magnificent whale surfaced near the boat and the cetacean sprayed water skyward",
    "The mechanic inspected the engine thoroughly and the technician replaced the worn parts",
    "An unexpected letter arrived this morning and the message contained surprising news",
    "The farmer harvested the wheat in August and the grower stored it in barns",
    "A bright comet appeared in the evening sky and the meteor was visible for weeks",
    "The journalist investigated the corruption scandal and the reporter published a detailed expose",
    "A stray kitten wandered into the garage and the cat found shelter from the storm",
    "The surgeon performed the operation successfully and the doctor spoke with the family afterward",
    "An old photograph fell from the album and the picture showed a forgotten relative",
    "The violinist tuned her instrument backstage and the cellist played flawlessly during the concert",
    "A dense fog rolled in from the harbor and the mist obscured the entire coastline",
    "The archaeologist uncovered ancient pottery fragments and the historian documented every finding",
    "A young eagle soared above the canyon and the hawk spotted prey far below",
    "The carpenter built a beautiful bookshelf and the craftsman finished it with dark walnut stain",
    "An important meeting was scheduled for noon and the conference lasted well into the evening",
    "The volcano erupted without any warning and the mountain sent ash clouds miles high",
    "A talented sculptor shaped the marble block and the artisan revealed an astonishing figure",
    "The astronomer observed a distant galaxy cluster and the physicist recorded the spectral data",
    "An enormous bear emerged from the forest and the grizzly ambled toward the river",
    "The conductor raised the baton slowly and the maestro began the symphony with a whisper",
    "A mysterious stranger appeared at the door and the visitor asked for directions to town",
    "The gardener planted roses along the path and the botanist watered them every morning",
    "An abandoned factory stood at the edge of town and the warehouse was scheduled for demolition",
    "The ambassador delivered a speech at the summit and the diplomat proposed a new alliance",
    "A playful dolphin leaped beside the kayak and the porpoise followed us for a mile",
    "The electrician rewired the entire basement and the technician installed new circuit breakers",
    "An unusual butterfly landed on my hand and the moth stayed for several minutes",
    "The philosopher debated the nature of consciousness and the thinker wrote extensively about free will",
    "A severe drought affected the entire region and the famine destroyed most of the crops",
    "The pianist practiced the sonata for months and the keyboardist performed it at Carnegie Hall",
    "An intricate mosaic decorated the entrance hall and the mural depicted scenes from ancient mythology",
    "The firefighter rushed into the burning building and the paramedic rescued three trapped residents",
    "A gentle breeze rustled through the wheat field and the wind carried the scent of lavender",
    "The mathematician proved the conjecture after decades and the scholar received international recognition",
    "An ornate mirror hung above the fireplace and the glass reflected the entire drawing room",
    "The translator worked on the manuscript for a year and the interpreter preserved every subtle nuance",
    "A massive glacier carved through the mountain range and the icefield left deep valleys behind",
    "The biologist discovered a new species of moth and the naturalist named it after her mentor",
    "An express train departed from the central station and the locomotive arrived exactly on schedule",
    "The photographer captured the sunset over the desert and the cameraman sold the image to a magazine",
    "A sudden thunderstorm interrupted the outdoor wedding and the squall passed within twenty minutes",
    "The blacksmith forged a sword from raw iron and the metalworker tempered it in cold water",
    "An exotic orchid bloomed in the greenhouse and the flower attracted dozens of admiring visitors",
    "The senator introduced a controversial bill and the legislator defended it during heated debate",
    "A coral reef stretched for miles along the coast and the atoll supported thousands of marine species",
    "The poet composed verses by candlelight and the lyricist published them in a slim volume",
    "An enormous wave crashed against the seawall and the surge flooded the promenade completely",
    "The locksmith opened the antique safe carefully and the specialist found old documents inside",
    "A brilliant rainbow arched across the valley and the spectrum faded slowly as the sun set",
    "The geologist examined the rock formation closely and the mineralogist estimated it was millions of years old",
    "An elegant heron stood motionless in the shallows and the crane struck at a fish suddenly",
    "The plumber fixed the leaking pipe overnight and the repairman charged a reasonable price",
    "A rare eclipse darkened the afternoon sky and the occultation lasted for nearly four minutes",
    "The weaver created tapestries of extraordinary detail and the spinner sold them at the local market",
    "An icy wind swept down from the mountains and the gale brought the first snow of winter",
    "The curator arranged the exhibition thoughtfully and the director wrote descriptions for every piece",
    "A towering redwood dominated the forest clearing and the sequoia was estimated to be two thousand years old",
    "The chemist analyzed the unknown compound and the scientist determined its molecular structure",
    "An old bridge spanned the wide river and the viaduct had been standing for three centuries",
    "The beekeeper tended the hives each morning and the apiarist harvested golden honey in autumn",
    "A sleek submarine descended into the abyss and the vessel mapped the ocean floor below",
    "The jeweler examined the diamond under bright light and the appraiser declared it virtually flawless",
    "An ancient manuscript was found in the monastery and the scroll contained previously unknown texts",
    "The quarterback threw a perfect spiral downfield and the passer led the team to victory",
    "A dense jungle surrounded the hidden temple and the rainforest had reclaimed most of the ruins",
    "The optician fitted the new lenses precisely and the ophthalmologist adjusted the frame for comfort",
]

# Trim all lists to 100
EXACT_REPEAT = EXACT_REPEAT[:100]
NO_REPEAT = NO_REPEAT[:100]
SEMANTIC_NEAR = SEMANTIC_NEAR[:100]

# Add missing semantic sentences to reach 100
while len(SEMANTIC_NEAR) < 100:
    SEMANTIC_NEAR.append(SEMANTIC_NEAR[len(SEMANTIC_NEAR) - 96])  # pad from start of extras

assert len(EXACT_REPEAT) == 100, f"Expected 100 exact repeat, got {len(EXACT_REPEAT)}"
assert len(NO_REPEAT) == 100, f"Expected 100 no repeat, got {len(NO_REPEAT)}"
assert len(SEMANTIC_NEAR) == 100, f"Expected 100 semantic near, got {len(SEMANTIC_NEAR)}"

print(f"✅ Stimulus set: {len(EXACT_REPEAT)} exact repeat, {len(NO_REPEAT)} no repeat, {len(SEMANTIC_NEAR)} semantic near-miss")
print(f"   Total: {len(EXACT_REPEAT) + len(NO_REPEAT) + len(SEMANTIC_NEAR)} sentences")
